name: Build extensions/index.html

on: push

jobs:
  generate_html:
    runs-on: ubuntu-18.04
    steps:
      - name: Get repo
        uses: actions/checkout@v2
      - name: Generate extensions/index.html
        uses: docker://pandoc/core:2.9
        with:
          args: --output=extensions/index.html extensions/index.md
      - name: Commit extensions/index.html
        uses: EndBug/add-and-commit@v5
        with:
          message: "Add newly generated extensions/index.html by GitHub Actions."
          add: "extensions/index.html --force"