name: Build extensions/index.html

on: push

jobs:
  generate_html:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/core:2.9
        with:
          args: --output=extensions/index.html extensions/index.md
