name: Build ide-extensions/index.html

on: push

jobs:
  generate_html:
    runs-on: ubuntu-18.04
    steps:
      - name: Get repo
        uses: actions/checkout@v2
      - name: Generate ide-extensions/index.html
        uses: docker://pandoc/core:2.9
        with:
          args: >
            --output=ide-extensions/index.html
            --css=github-pandoc.css
            --standalone
            ide-extensions/index.md
      - name: Commit ide-extensions/index.html
        uses: EndBug/add-and-commit@v5
        with:
          message: "Add newly generated ide-extensions/index.html by GitHub Actions."
          add: "ide-extensions/index.html --force"